import type { Client } from '../types/client';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 1,
    lastName: 'Петров',
    firstName: 'Андрей',
    patronymic: 'Сергеевич',
    email: 'petrov@mail.ru',
    phone: '+7 927 112-34-56',
    calculationsCount: 2,
    status: 'active',
    createdAt: '2021-01-15',
  },
  {
    id: 2,
    lastName: 'Смирнова',
    firstName: 'Ольга',
    patronymic: 'Ивановна',
    email: 'smirnova@mail.ru',
    phone: '+7 927 223-45-67',
    calculationsCount: 1,
    status: 'contract',
    createdAt: '2021-01-12',
  },
  {
    id: 3,
    lastName: 'Козлов',
    firstName: 'Виктор',
    patronymic: 'Петрович',
    email: 'kozlov@mail.ru',
    phone: '+7 917 334-56-78',
    calculationsCount: 3,
    status: 'inactive',
    createdAt: '2021-01-08',
  },
  {
    id: 4,
    lastName: 'Николаева',
    firstName: 'Светлана',
    phone: '+7 927 445-67-89',
    calculationsCount: 1,
    status: 'new',
    createdAt: '2021-01-05',
  },
  {
    id: 5,
    lastName: 'Захаров',
    firstName: 'Игорь',
    patronymic: 'Дмитриевич',
    email: 'zakharov@yandex.ru',
    phone: '+7 905 556-78-90',
    calculationsCount: 0,
    status: 'new',
    createdAt: '2021-01-03',
  },
  {
    id: 6,
    lastName: 'Морозова',
    firstName: 'Елена',
    patronymic: 'Александровна',
    email: 'morozova@gmail.com',
    phone: '+7 917 667-89-01',
    calculationsCount: 4,
    status: 'contract',
    createdAt: '2020-12-28',
  },
];
